name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,arm/v7,s390x,ppc64le

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure build revision
        id: vars
        run: echo "::set-output name=sha_short::${GITHUB_SHA:0:7}"

      - name: Build images
        env:
          BUILDREV: ${{ steps.vars.outputs.sha_short }}
        run: docker buildx bake --pull

      # - name: Push images
      #   env:
      #     BUILDREV: ${{ steps.vars.outputs.sha_short }}
      #   run: docker buildx bake --push